import type { Finding, ScanBatch } from "./types";

function uid(prefix = "f"): string {
  return `${prefix}_${Math.random().toString(36).slice(2, 9)}`;
}

export interface SampleDataResult {
  findings: Finding[];
  batches: ScanBatch[];
}

export function generateSampleData(): SampleDataResult {
  const batch1Id = "scan_sample_infra";
  const batch2Id = "scan_sample_web";

  const batch1: ScanBatch = {
    id: batch1Id,
    label: "Internal Infrastructure Scan",
    date: "2026-07-01",
    tool: "Nessus",
    findingCount: 18,
  };

  const batch2: ScanBatch = {
    id: batch2Id,
    label: "External Web Penetration Test",
    date: "2026-07-15",
    tool: "Burp Suite",
    findingCount: 12,
  };

  const infraFindings: Finding[] = [
    {
      id: uid(),
      scanId: batch1Id,
      scanLabel: batch1.label,
      scanDate: "2026-07-01T08:00:00Z",
      tool: "Nessus",
      host: "10.100.1.10",
      port: "443",
      protocol: "tcp",
      name: "SSL/TLS Protocol Initialization Vector Toggle Weakness (BEAST)",
      severity: "Medium",
      cvss: 4.3,
      cve: ["CVE-2011-3389"],
      description: "The SSL protocol, as used in certain configurations, allows man-in-the-middle attackers to obtain plaintext data via a chosen-plaintext attack on a block cipher.",
      solution: "Configure SSL/TLS servers to use TLS 1.2 or higher. Disable CBC-mode ciphers in SSLv3/TLS 1.0.",
      pluginId: "56203",
    },
    {
      id: uid(),
      scanId: batch1Id,
      scanLabel: batch1.label,
      scanDate: "2026-07-01T08:00:00Z",
      tool: "Nessus",
      host: "10.100.1.10",
      port: "22",
      protocol: "tcp",
      name: "SSH Weak Algorithms Supported",
      severity: "Low",
      cvss: 2.6,
      cve: [],
      description: "The remote SSH server is configured to support weak MAC algorithms or weak encryption key exchange algorithms.",
      solution: "Disable weak HMAC algorithms (e.g., hmac-md5, hmac-sha1-96) and weak ciphers (e.g., 3des-cbc).",
      pluginId: "70658",
    },
    {
      id: uid(),
      scanId: batch1Id,
      scanLabel: batch1.label,
      scanDate: "2026-07-01T08:00:00Z",
      tool: "Nessus",
      host: "10.100.1.25",
      port: "445",
      protocol: "tcp",
      name: "Microsoft Windows SMBv1 Multiple Vulnerabilities (EternalBlue)",
      severity: "Critical",
      cvss: 9.3,
      cve: ["CVE-2017-0143", "CVE-2017-0144", "CVE-2017-0145"],
      description: "An unauthenticated remote attacker can exploit these vulnerabilities to execute arbitrary code with SYSTEM privileges on the affected host via crafted SMB requests.",
      solution: "Disable SMBv1 and apply the MS17-010 security update.",
      pluginId: "97994",
    },
    {
      id: uid(),
      scanId: batch1Id,
      scanLabel: batch1.label,
      scanDate: "2026-07-01T08:00:00Z",
      tool: "Nessus",
      host: "10.100.1.25",
      port: "139",
      protocol: "tcp",
      name: "Microsoft Windows SMB NULL Session Authentication Allowed",
      severity: "Medium",
      cvss: 5.0,
      cve: ["CVE-1999-0519"],
      description: "An unauthenticated remote attacker can establish an anonymous/null session to retrieve security policies, domain structures, and list usernames.",
      solution: "Configure RestrictAnonymous setting in the Windows Registry to restrict null sessions.",
      pluginId: "26920",
    },
    {
      id: uid(),
      scanId: batch1Id,
      scanLabel: batch1.label,
      scanDate: "2026-07-01T08:00:00Z",
      tool: "Nessus",
      host: "10.100.2.5",
      port: "80",
      protocol: "tcp",
      name: "Apache HTTP Server Directory Traversal Vulnerability",
      severity: "High",
      cvss: 7.5,
      cve: ["CVE-2021-41773"],
      description: "A directory traversal and subsequent file disclosure vulnerability was found in Apache HTTP Server 2.4.49. An attacker could use a path traversal attack to map URLs to files outside the document root.",
      solution: "Upgrade Apache HTTP Server to version 2.4.51 or later.",
      pluginId: "153896",
    },
    {
      id: uid(),
      scanId: batch1Id,
      scanLabel: batch1.label,
      scanDate: "2026-07-01T08:00:00Z",
      tool: "Nessus",
      host: "10.100.2.5",
      port: "80",
      protocol: "tcp",
      name: "HTTP Server Wildcard SSL Certificate Expiration",
      severity: "Low",
      cvss: 3.2,
      cve: [],
      description: "The SSL certificate for the remote HTTP service will expire within the next 30 days.",
      solution: "Renew the SSL certificate.",
      pluginId: "12345",
    },
    {
      id: uid(),
      scanId: batch1Id,
      scanLabel: batch1.label,
      scanDate: "2026-07-01T08:00:00Z",
      tool: "Nessus",
      host: "10.100.2.12",
      port: "3306",
      protocol: "tcp",
      name: "MySQL Server Outdated Version (Multiple Vulnerabilities)",
      severity: "High",
      cvss: 8.8,
      cve: ["CVE-2021-2169", "CVE-2021-2179"],
      description: "The MySQL installation on the remote host is running a version older than 8.0.25. It is affected by multiple vulnerabilities that could result in unauthorized data exposure or denial of service.",
      solution: "Upgrade MySQL server to version 8.0.25 or higher.",
      pluginId: "114002",
    },
    {
      id: uid(),
      scanId: batch1Id,
      scanLabel: batch1.label,
      scanDate: "2026-07-01T08:00:00Z",
      tool: "Nessus",
      host: "10.100.2.12",
      port: "3306",
      protocol: "tcp",
      name: "MySQL Server Default Accounts / Empty Root Password",
      severity: "Critical",
      cvss: 9.8,
      cve: [],
      description: "The MySQL database server has an account with a default username or an empty password for administrative roles, allowing full administrative control to remote users.",
      solution: "Run mysql_secure_installation and set a strong root password.",
      pluginId: "10112",
    },
    {
      id: uid(),
      scanId: batch1Id,
      scanLabel: batch1.label,
      scanDate: "2026-07-01T08:00:00Z",
      tool: "Nessus",
      host: "10.100.1.10",
      port: "443",
      protocol: "tcp",
      name: "HTTP Strict Transport Security (HSTS) Header Missing",
      severity: "Info",
      cvss: 0.0,
      cve: [],
      description: "The remote web server does not enforce HTTP Strict Transport Security (HSTS).",
      solution: "Configure the web server to send the 'Strict-Transport-Security' response header.",
      pluginId: "84821",
    },
    {
      id: uid(),
      scanId: batch1Id,
      scanLabel: batch1.label,
      scanDate: "2026-07-01T08:00:00Z",
      tool: "Nessus",
      host: "10.100.1.25",
      port: "445",
      protocol: "tcp",
      name: "SMB Signing Not Required",
      severity: "Medium",
      cvss: 5.0,
      cve: [],
      description: "Signing is not required on the remote SMB server. An unauthenticated, remote attacker can exploit this to conduct man-in-the-middle attacks.",
      solution: "Enforce SMB signing in host configuration.",
      pluginId: "57608",
    },
    {
      id: uid(),
      scanId: batch1Id,
      scanLabel: batch1.label,
      scanDate: "2026-07-01T08:00:00Z",
      tool: "Nessus",
      host: "10.100.1.10",
      port: "8080",
      protocol: "tcp",
      name: "Apache Tomcat default files / examples",
      severity: "Low",
      cvss: 3.5,
      cve: [],
      description: "Tomcat default files or example scripts are installed on the remote host, which could leak system configuration or aid reconnaissance.",
      solution: "Undeploy default example applications.",
      pluginId: "12301",
    },
    {
      id: uid(),
      scanId: batch1Id,
      scanLabel: batch1.label,
      scanDate: "2026-07-01T08:00:00Z",
      tool: "Nessus",
      host: "10.100.2.12",
      port: "3306",
      protocol: "tcp",
      name: "MySQL Encryption in Transit Disabled",
      severity: "Medium",
      cvss: 5.9,
      cve: [],
      description: "The remote database connection is not encrypted by default, allowing sniffing of credentials and database queries.",
      solution: "Enable SSL/TLS requirement for database users.",
      pluginId: "11993",
    },
    {
      id: uid(),
      scanId: batch1Id,
      scanLabel: batch1.label,
      scanDate: "2026-07-01T08:00:00Z",
      tool: "Nessus",
      host: "10.100.2.5",
      port: "80",
      protocol: "tcp",
      name: "Apache HTTP Server mod_proxy Request SSRF",
      severity: "High",
      cvss: 8.6,
      cve: ["CVE-2021-40438"],
      description: "A crafted request URI-path can cause mod_proxy to forward requests to an arbitrary origin server, leading to Server-Side Request Forgery.",
      solution: "Update Apache to 2.4.51 or apply the relevant patch.",
      pluginId: "153902",
    },
    {
      id: uid(),
      scanId: batch1Id,
      scanLabel: batch1.label,
      scanDate: "2026-07-01T08:00:00Z",
      tool: "Nessus",
      host: "10.100.1.10",
      port: "8080",
      protocol: "tcp",
      name: "Tomcat Remote Code Execution via JSP Upload",
      severity: "Critical",
      cvss: 9.8,
      cve: ["CVE-2017-12617"],
      description: "When running on Windows with HTTP PUT enabled, an attacker can upload a malicious JSP file to execute arbitrary code.",
      solution: "Upgrade to Tomcat 8.5.23 or newer, or disable write capabilities.",
      pluginId: "103782",
    },
    {
      id: uid(),
      scanId: batch1Id,
      scanLabel: batch1.label,
      scanDate: "2026-07-01T08:00:00Z",
      tool: "Nessus",
      host: "10.100.2.12",
      port: "22",
      protocol: "tcp",
      name: "SSH Server Banner Disclosure",
      severity: "Info",
      cvss: 0.0,
      cve: [],
      description: "The remote SSH server discloses its version banner.",
      solution: "Configure SSH to hide version details or suppress banners.",
      pluginId: "10092",
    },
    {
      id: uid(),
      scanId: batch1Id,
      scanLabel: batch1.label,
      scanDate: "2026-07-01T08:00:00Z",
      tool: "Nessus",
      host: "10.100.2.5",
      port: "80",
      protocol: "tcp",
      name: "HTTP Server Banner Disclosure",
      severity: "Info",
      cvss: 0.0,
      cve: [],
      description: "The remote web server returns version details in Server response headers.",
      solution: "Configure ServerTokens Prod and ServerSignature Off.",
      pluginId: "10093",
    },
    {
      id: uid(),
      scanId: batch1Id,
      scanLabel: batch1.label,
      scanDate: "2026-07-01T08:00:00Z",
      tool: "Nessus",
      host: "10.100.1.10",
      port: "443",
      protocol: "tcp",
      name: "SSL Certificate Self-Signed",
      severity: "Medium",
      cvss: 5.3,
      cve: [],
      description: "The remote host uses a self-signed SSL certificate, which does not allow authentication of server identity.",
      solution: "Purchase or obtain a valid certificate from a trusted authority.",
      pluginId: "10863",
    },
    {
      id: uid(),
      scanId: batch1Id,
      scanLabel: batch1.label,
      scanDate: "2026-07-01T08:00:00Z",
      tool: "Nessus",
      host: "10.100.1.25",
      port: "445",
      protocol: "tcp",
      name: "SMB Registry Access Allowed",
      severity: "Low",
      cvss: 3.1,
      cve: [],
      description: "Remote access to the Windows registry is allowed, enabling potential reconnaissance.",
      solution: "Disable the Remote Registry service or restrict access.",
      pluginId: "26922",
    }
  ];

  const webFindings: Finding[] = [
    {
      id: uid(),
      scanId: batch2Id,
      scanLabel: batch2.label,
      scanDate: "2026-07-15T12:00:00Z",
      tool: "Burp Suite",
      host: "vaptlens.com",
      port: "443",
      protocol: "https",
      name: "SQL Injection in Search Query parameter",
      severity: "Critical",
      cvss: 9.4,
      cve: ["CVE-2026-9999"],
      description: "The application parses user inputs in search functions directly inside a SQL query, allowing database command injection.",
      solution: "Use parameterized SQL queries / Prepared Statements for all database queries.",
      pluginId: "issue-sql-inj",
    },
    {
      id: uid(),
      scanId: batch2Id,
      scanLabel: batch2.label,
      scanDate: "2026-07-15T12:00:00Z",
      tool: "Burp Suite",
      host: "vaptlens.com",
      port: "443",
      protocol: "https",
      name: "Reflected Cross-Site Scripting (XSS) in Login Page",
      severity: "High",
      cvss: 7.2,
      cve: [],
      description: "User inputs returned from login redirections are rendered directly into HTML without sanitization or encoding.",
      solution: "Apply HTML entity encoding to user inputs before printing them in HTML templates.",
      pluginId: "issue-xss-reflected",
    },
    {
      id: uid(),
      scanId: batch2Id,
      scanLabel: batch2.label,
      scanDate: "2026-07-15T12:00:00Z",
      tool: "Burp Suite",
      host: "api.vaptlens.com",
      port: "443",
      protocol: "https",
      name: "Broken Object Level Authorization (BOLA)",
      severity: "High",
      cvss: 8.5,
      cve: [],
      description: "The API endpoint /api/users/{id}/profile fails to validate if the authenticated user has rights to request the given ID.",
      solution: "Enforce server-side user ownership verification on every resource endpoint.",
      pluginId: "issue-bola",
    },
    {
      id: uid(),
      scanId: batch2Id,
      scanLabel: batch2.label,
      scanDate: "2026-07-15T12:00:00Z",
      tool: "Burp Suite",
      host: "vaptlens.com",
      port: "443",
      protocol: "https",
      name: "Cross-Site Request Forgery (CSRF) in Password Reset",
      severity: "High",
      cvss: 8.1,
      cve: [],
      description: "State-changing actions on profile changes lack anti-CSRF token protection, leaving users vulnerable to session hijack operations.",
      solution: "Add unique cryptographic anti-CSRF tokens to all POST/PATCH forms.",
      pluginId: "issue-csrf",
    },
    {
      id: uid(),
      scanId: batch2Id,
      scanLabel: batch2.label,
      scanDate: "2026-07-15T12:00:00Z",
      tool: "Burp Suite",
      host: "api.vaptlens.com",
      port: "443",
      protocol: "https",
      name: "CORS Misconfiguration Allows Arbitrary Origin Access",
      severity: "Medium",
      cvss: 6.5,
      cve: [],
      description: "Access-Control-Allow-Origin header is set to reflect the incoming Origin header dynamically with credentials allowed.",
      solution: "Do not dynamically mirror origins with credentials enabled. Maintain a strict whitelist.",
      pluginId: "issue-cors-misconfig",
    },
    {
      id: uid(),
      scanId: batch2Id,
      scanLabel: batch2.label,
      scanDate: "2026-07-15T12:00:00Z",
      tool: "Burp Suite",
      host: "vaptlens.com",
      port: "443",
      protocol: "https",
      name: "Password policy strength insufficient",
      severity: "Medium",
      cvss: 5.2,
      cve: [],
      description: "The application accepts weak passwords with less than 8 characters and no special character requirements.",
      solution: "Implement robust password complexity controls requiring at least 12 characters, including alphanumeric and symbols.",
      pluginId: "issue-weak-pwd",
    },
    {
      id: uid(),
      scanId: batch2Id,
      scanLabel: batch2.label,
      scanDate: "2026-07-15T12:00:00Z",
      tool: "Burp Suite",
      host: "vaptlens.com",
      port: "443",
      protocol: "https",
      name: "Cookie Missing Secure Attribute",
      severity: "Medium",
      cvss: 4.8,
      cve: [],
      description: "Session identifiers and security cookies are set without the Secure attribute, exposing them to cleartext transmission.",
      solution: "Set the Secure flag on all session cookies.",
      pluginId: "issue-cookie-secure",
    },
    {
      id: uid(),
      scanId: batch2Id,
      scanLabel: batch2.label,
      scanDate: "2026-07-15T12:00:00Z",
      tool: "Burp Suite",
      host: "vaptlens.com",
      port: "443",
      protocol: "https",
      name: "Cookie Missing HttpOnly Attribute",
      severity: "Medium",
      cvss: 4.8,
      cve: [],
      description: "Session cookies lack the HttpOnly attribute, allowing access via client-side javascript (enhancing XSS impact).",
      solution: "Set HttpOnly flag on all cookies storing sensitive user session state.",
      pluginId: "issue-cookie-httponly",
    },
    {
      id: uid(),
      scanId: batch2Id,
      scanLabel: batch2.label,
      scanDate: "2026-07-15T12:00:00Z",
      tool: "Burp Suite",
      host: "vaptlens.com",
      port: "443",
      protocol: "https",
      name: "HTTP Trace Method Enabled",
      severity: "Low",
      cvss: 3.5,
      cve: ["CVE-2004-2320"],
      description: "HTTP TRACE method is enabled on the remote server, allowing Cross-Site Tracing attacks.",
      solution: "Disable TRACE method in web server config (e.g. TraceEnable Off).",
      pluginId: "issue-trace-enabled",
    },
    {
      id: uid(),
      scanId: batch2Id,
      scanLabel: batch2.label,
      scanDate: "2026-07-15T12:00:00Z",
      tool: "Burp Suite",
      host: "api.vaptlens.com",
      port: "443",
      protocol: "https",
      name: "API Information Leakage via Stack Trace",
      severity: "Low",
      cvss: 2.1,
      cve: [],
      description: "The API endpoint throws a raw stack trace upon receiving invalid JSON format, disclosing internal paths and libraries.",
      solution: "Catch parser exceptions on server and return generic JSON errors.",
      pluginId: "issue-stack-trace",
    },
    {
      id: uid(),
      scanId: batch2Id,
      scanLabel: batch2.label,
      scanDate: "2026-07-15T12:00:00Z",
      tool: "Burp Suite",
      host: "vaptlens.com",
      port: "443",
      protocol: "https",
      name: "Web Server Directory Indexing Enabled",
      severity: "Low",
      cvss: 3.1,
      cve: [],
      description: "Web server displays file lists for directories lacking index.html.",
      solution: "Disable directory listings in configuration (Options -Indexes).",
      pluginId: "issue-directory-index",
    },
    {
      id: uid(),
      scanId: batch2Id,
      scanLabel: batch2.label,
      scanDate: "2026-07-15T12:00:00Z",
      tool: "Burp Suite",
      host: "vaptlens.com",
      port: "443",
      protocol: "https",
      name: "X-Content-Type-Options Header Missing",
      severity: "Info",
      cvss: 0.0,
      cve: [],
      description: "The X-Content-Type-Options response header is not set to nosniff, exposing users to mime sniffing.",
      solution: "Send 'X-Content-Type-Options: nosniff' header.",
      pluginId: "issue-xcontent-type",
    }
  ];

  return {
    findings: [...infraFindings, ...webFindings],
    batches: [batch1, batch2],
  };
}
