import type { Finding, ScanBatch } from "./types";

function uid(prefix = "f"): string {
  return `${prefix}_${Math.random().toString(36).slice(2, 9)}`;
}

export interface SampleDataResult {
  findings: Finding[];
  batches: ScanBatch[];
}

export function generateSampleData(): SampleDataResult {
  const batch1Id = "scan_sample_q4_2025";
  const batch2Id = "scan_sample_q1_2026";
  const batch3Id = "scan_sample_q2_2026";

  const batch1: ScanBatch = {
    id: batch1Id,
    label: "Infrastructure Scan - Q4 2025",
    date: "2025-11-15",
    tool: "Nessus",
    findingCount: 6,
  };

  const batch2: ScanBatch = {
    id: batch2Id,
    label: "Infrastructure Scan - Q1 2026",
    date: "2026-02-15",
    tool: "Nessus",
    findingCount: 6,
  };

  const batch3: ScanBatch = {
    id: batch3Id,
    label: "Infrastructure & Web Scan - Q2 2026",
    date: "2026-07-01",
    tool: "Nessus",
    findingCount: 22,
  };

  // Findings in Q4 2025 (Batch 1)
  const q4Findings: Finding[] = [
    {
      id: "f_eb_q4",
      scanId: batch1Id,
      scanLabel: batch1.label,
      scanDate: "2025-11-15T08:00:00Z",
      tool: "Nessus",
      host: "10.100.1.25",
      port: "445",
      protocol: "tcp",
      name: "Microsoft Windows SMBv1 Multiple Vulnerabilities (EternalBlue)",
      severity: "Critical",
      cvss: 9.3,
      cve: ["CVE-2017-0143", "CVE-2017-0144"],
      description: "An unauthenticated remote attacker can exploit these vulnerabilities to execute arbitrary code with SYSTEM privileges.",
      solution: "Disable SMBv1 and apply the MS17-010 security update.",
      pluginId: "97994",
    },
    {
      id: "f_my_q4",
      scanId: batch1Id,
      scanLabel: batch1.label,
      scanDate: "2025-11-15T08:00:00Z",
      tool: "Nessus",
      host: "10.100.2.12",
      port: "3306",
      protocol: "tcp",
      name: "MySQL Server Default Accounts / Empty Root Password",
      severity: "Critical",
      cvss: 9.8,
      cve: [],
      description: "The MySQL database server has an account with a default username or empty root password.",
      solution: "Run mysql_secure_installation and set a strong root password.",
      pluginId: "10112",
    },
    {
      id: "f_smb_q4",
      scanId: batch1Id,
      scanLabel: batch1.label,
      scanDate: "2025-11-15T08:00:00Z",
      tool: "Nessus",
      host: "10.100.1.25",
      port: "139",
      protocol: "tcp",
      name: "Microsoft Windows SMB NULL Session Authentication Allowed",
      severity: "Medium",
      cvss: 5.0,
      cve: ["CVE-1999-0519"],
      description: "An unauthenticated remote attacker can establish an anonymous null session to retrieve domain policies and list users.",
      solution: "Configure RestrictAnonymous setting in the registry.",
      pluginId: "26920",
    },
    {
      id: "f_ssh_q4",
      scanId: batch1Id,
      scanLabel: batch1.label,
      scanDate: "2025-11-15T08:00:00Z",
      tool: "Nessus",
      host: "10.100.1.10",
      port: "22",
      protocol: "tcp",
      name: "SSH Weak Algorithms Supported",
      severity: "Low",
      cvss: 2.6,
      cve: [],
      description: "The remote SSH server is configured to support weak MAC or encryption algorithms.",
      solution: "Disable weak HMAC algorithms and CBC ciphers.",
      pluginId: "70658",
    },
    {
      id: "f_ssl_q4",
      scanId: batch1Id,
      scanLabel: batch1.label,
      scanDate: "2025-11-15T08:00:00Z",
      tool: "Nessus",
      host: "10.100.1.10",
      port: "443",
      protocol: "tcp",
      name: "SSL Certificate Self-Signed",
      severity: "Medium",
      cvss: 5.3,
      cve: [],
      description: "The remote host uses a self-signed SSL certificate.",
      solution: "Obtain a valid certificate from a trusted authority.",
      pluginId: "10863",
    },
    {
      id: "f_http_q4",
      scanId: batch1Id,
      scanLabel: batch1.label,
      scanDate: "2025-11-15T08:00:00Z",
      tool: "Nessus",
      host: "10.100.2.5",
      port: "80",
      protocol: "tcp",
      name: "HTTP Server Banner Disclosure",
      severity: "Info",
      cvss: 0.0,
      cve: [],
      description: "The remote web server returns version details in Server response headers.",
      solution: "Configure ServerTokens Prod and ServerSignature Off.",
      pluginId: "10093",
    },
  ];

  // Findings in Q1 2026 (Batch 2)
  const q1Findings: Finding[] = [
    // Persistent from Q4 2025
    {
      id: "f_my_q1",
      scanId: batch2Id,
      scanLabel: batch2.label,
      scanDate: "2025-11-15T08:00:00Z",
      tool: "Nessus",
      host: "10.100.2.12",
      port: "3306",
      protocol: "tcp",
      name: "MySQL Server Default Accounts / Empty Root Password",
      severity: "Critical",
      cvss: 9.8,
      cve: [],
      description: "The MySQL database server has an account with a default username or empty root password.",
      solution: "Run mysql_secure_installation and set a strong root password.",
      pluginId: "10112",
    },
    {
      id: "f_smb_q1",
      scanId: batch2Id,
      scanLabel: batch2.label,
      scanDate: "2025-11-15T08:00:00Z",
      tool: "Nessus",
      host: "10.100.1.25",
      port: "139",
      protocol: "tcp",
      name: "Microsoft Windows SMB NULL Session Authentication Allowed",
      severity: "Medium",
      cvss: 5.0,
      cve: ["CVE-1999-0519"],
      description: "An unauthenticated remote attacker can establish an anonymous null session to retrieve domain policies and list users.",
      solution: "Configure RestrictAnonymous setting in the registry.",
      pluginId: "26920",
    },
    {
      id: "f_ssh_q1",
      scanId: batch2Id,
      scanLabel: batch2.label,
      scanDate: "2025-11-15T08:00:00Z",
      tool: "Nessus",
      host: "10.100.1.10",
      port: "22",
      protocol: "tcp",
      name: "SSH Weak Algorithms Supported",
      severity: "Low",
      cvss: 2.6,
      cve: [],
      description: "The remote SSH server is configured to support weak MAC or encryption algorithms.",
      solution: "Disable weak HMAC algorithms and CBC ciphers.",
      pluginId: "70658",
    },
    {
      id: "f_ssl_q1",
      scanId: batch2Id,
      scanLabel: batch2.label,
      scanDate: "2025-11-15T08:00:00Z",
      tool: "Nessus",
      host: "10.100.1.10",
      port: "443",
      protocol: "tcp",
      name: "SSL Certificate Self-Signed",
      severity: "Medium",
      cvss: 5.3,
      cve: [],
      description: "The remote host uses a self-signed SSL certificate.",
      solution: "Obtain a valid certificate from a trusted authority.",
      pluginId: "10863",
    },
    // New findings in Q1 2026
    {
      id: "f_ap_q1",
      scanId: batch2Id,
      scanLabel: batch2.label,
      scanDate: "2026-02-15T09:00:00Z",
      tool: "Nessus",
      host: "10.100.2.5",
      port: "80",
      protocol: "tcp",
      name: "Apache HTTP Server Directory Traversal Vulnerability",
      severity: "High",
      cvss: 7.5,
      cve: ["CVE-2021-41773"],
      description: "A directory traversal and subsequent file disclosure vulnerability was found in Apache HTTP Server 2.4.49.",
      solution: "Upgrade Apache HTTP Server to version 2.4.51 or later.",
      pluginId: "153896",
    },
    {
      id: "f_my_out_q1",
      scanId: batch2Id,
      scanLabel: batch2.label,
      scanDate: "2026-02-15T09:00:00Z",
      tool: "Nessus",
      host: "10.100.2.12",
      port: "3306",
      protocol: "tcp",
      name: "MySQL Server Outdated Version (Multiple Vulnerabilities)",
      severity: "High",
      cvss: 8.8,
      cve: ["CVE-2021-2169", "CVE-2021-2179"],
      description: "The MySQL installation is outdated (EOL/Obsolete) and is affected by multiple vulnerabilities.",
      solution: "Upgrade MySQL server to version 8.0.25 or higher.",
      pluginId: "114002",
    },
    {
      id: "f_hsts_q1",
      scanId: batch2Id,
      scanLabel: batch2.label,
      scanDate: "2026-02-15T09:00:00Z",
      tool: "Nessus",
      host: "10.100.1.10",
      port: "443",
      protocol: "tcp",
      name: "HTTP Strict Transport Security (HSTS) Header Missing",
      severity: "Info",
      cvss: 0.0,
      cve: [],
      description: "The remote web server does not enforce HTTP Strict Transport Security (HSTS).",
      solution: "Configure the web server to send the Strict-Transport-Security header.",
      pluginId: "84821",
    },
  ];

  // Findings in Q2 2026 (Batch 3)
  const q2Findings: Finding[] = [
    // Persistent from Q4 2025 / Q1 2026
    {
      id: "f_my_q2",
      scanId: batch3Id,
      scanLabel: batch3.label,
      scanDate: "2025-11-15T08:00:00Z", // Created Q4 2025 (>6 months ago)
      tool: "Nessus",
      host: "10.100.2.12",
      port: "3306",
      protocol: "tcp",
      name: "MySQL Server Default Accounts / Empty Root Password",
      severity: "Critical",
      cvss: 9.8,
      cve: [],
      description: "The MySQL database server has an account with a default username or empty root password.",
      solution: "Run mysql_secure_installation and set a strong root password.",
      pluginId: "10112",
    },
    {
      id: "f_ssh_q2",
      scanId: batch3Id,
      scanLabel: batch3.label,
      scanDate: "2025-11-15T08:00:00Z", // Created Q4 2025
      tool: "Nessus",
      host: "10.100.1.10",
      port: "22",
      protocol: "tcp",
      name: "SSH Weak Algorithms Supported",
      severity: "Low",
      cvss: 2.6,
      cve: [],
      description: "The remote SSH server is configured to support weak MAC or encryption algorithms.",
      solution: "Disable weak HMAC algorithms and CBC ciphers.",
      pluginId: "70658",
    },
    {
      id: "f_ssl_q2",
      scanId: batch3Id,
      scanLabel: batch3.label,
      scanDate: "2025-11-15T08:00:00Z", // Created Q4 2025
      tool: "Nessus",
      host: "10.100.1.10",
      port: "443",
      protocol: "tcp",
      name: "SSL Certificate Self-Signed",
      severity: "Medium",
      cvss: 5.3,
      cve: [],
      description: "The remote host uses a self-signed SSL certificate.",
      solution: "Obtain a valid certificate from a trusted authority.",
      pluginId: "10863",
    },
    {
      id: "f_my_out_q2",
      scanId: batch3Id,
      scanLabel: batch3.label,
      scanDate: "2026-02-15T09:00:00Z", // Created Q1 2026 (~4.5 months ago, SLA breached)
      tool: "Nessus",
      host: "10.100.2.12",
      port: "3306",
      protocol: "tcp",
      name: "MySQL Server Outdated Version (Multiple Vulnerabilities)",
      severity: "High",
      cvss: 8.8,
      cve: ["CVE-2021-2169", "CVE-2021-2179"],
      description: "The MySQL installation is outdated (EOL/Obsolete) and is affected by multiple vulnerabilities.",
      solution: "Upgrade MySQL server to version 8.0.25 or higher.",
      pluginId: "114002",
    },
    {
      id: "f_hsts_q2",
      scanId: batch3Id,
      scanLabel: batch3.label,
      scanDate: "2026-02-15T09:00:00Z",
      tool: "Nessus",
      host: "10.100.1.10",
      port: "443",
      protocol: "tcp",
      name: "HTTP Strict Transport Security (HSTS) Header Missing",
      severity: "Info",
      cvss: 0.0,
      cve: [],
      description: "The remote web server does not enforce HTTP Strict Transport Security (HSTS).",
      solution: "Configure the web server to send the Strict-Transport-Security header.",
      pluginId: "84821",
    },

    // New findings in Q2 2026
    {
      id: uid(),
      scanId: batch3Id,
      scanLabel: batch3.label,
      scanDate: "2026-07-01T10:00:00Z",
      tool: "Nessus",
      host: "10.100.1.10",
      port: "8080",
      protocol: "tcp",
      name: "Apache Tomcat Zero-Day Remote Code Execution",
      severity: "Critical",
      cvss: 9.8,
      cve: ["CVE-2026-9999"], // Zero-day!
      description: "A zero-day remote code execution vulnerability was identified in the Apache Tomcat servlet engine.",
      solution: "Apply the vendor hotfix immediately or disable the server.",
      pluginId: "109999",
    },
    {
      id: uid(),
      scanId: batch3Id,
      scanLabel: batch3.label,
      scanDate: "2026-07-01T12:00:00Z",
      tool: "Burp Suite",
      host: "vaptlens.com",
      port: "443",
      protocol: "https",
      name: "SQL Injection in Search Query parameter",
      severity: "Critical",
      cvss: 9.4,
      cve: ["CVE-2026-8888"], // Exploit!
      description: "The application parses user inputs in search queries directly inside a SQL query, allowing command injection.",
      solution: "Use parameterized SQL queries.",
      pluginId: "issue-sql-inj",
    },
    {
      id: uid(),
      scanId: batch3Id,
      scanLabel: batch3.label,
      scanDate: "2026-07-01T12:00:00Z",
      tool: "Burp Suite",
      host: "vaptlens.com",
      port: "443",
      protocol: "https",
      name: "Reflected Cross-Site Scripting (XSS) in Login Page",
      severity: "High",
      cvss: 7.2,
      cve: [],
      description: "User inputs returned from login redirections are rendered directly into HTML without sanitization.",
      solution: "Apply HTML entity encoding to user inputs.",
      pluginId: "issue-xss",
    },
    {
      id: uid(),
      scanId: batch3Id,
      scanLabel: batch3.label,
      scanDate: "2026-07-01T12:00:00Z",
      tool: "Burp Suite",
      host: "api.vaptlens.com",
      port: "443",
      protocol: "https",
      name: "Broken Object Level Authorization (BOLA)",
      severity: "High",
      cvss: 8.5,
      cve: [],
      description: "The API endpoint fails to validate user ownership rights of the requested profile ID.",
      solution: "Enforce server-side user ownership verification.",
      pluginId: "issue-bola",
    },
    {
      id: uid(),
      scanId: batch3Id,
      scanLabel: batch3.label,
      scanDate: "2026-07-01T12:00:00Z",
      tool: "Burp Suite",
      host: "vaptlens.com",
      port: "443",
      protocol: "https",
      name: "Cross-Site Request Forgery (CSRF) in Password Reset",
      severity: "High",
      cvss: 8.1,
      cve: [],
      description: "State-changing password reset forms lack anti-CSRF token protection.",
      solution: "Add unique cryptographic anti-CSRF tokens to all POST/PATCH forms.",
      pluginId: "issue-csrf",
    },
    {
      id: uid(),
      scanId: batch3Id,
      scanLabel: batch3.label,
      scanDate: "2026-07-01T10:00:00Z",
      tool: "Nessus",
      host: "10.100.1.10",
      port: "8080",
      protocol: "tcp",
      name: "Apache Tomcat EOL Version 6.0 Detection",
      severity: "Medium",
      cvss: 6.8,
      cve: [], // EOL!
      description: "The remote host is running Apache Tomcat 6.0, which is end-of-life (EOL/Obsolete).",
      solution: "Upgrade to a supported version of Apache Tomcat.",
      pluginId: "12301",
    },
    {
      id: uid(),
      scanId: batch3Id,
      scanLabel: batch3.label,
      scanDate: "2026-07-01T10:00:00Z",
      tool: "Nessus",
      host: "10.100.1.10",
      port: "443",
      protocol: "tcp",
      name: "SSL/TLS Protocol Initialization Vector Toggle Weakness (BEAST)",
      severity: "Medium",
      cvss: 4.3,
      cve: ["CVE-2011-3389"],
      description: "The SSL protocol allows chosen-plaintext attacks on CBC-mode ciphers.",
      solution: "Configure SSL/TLS servers to use TLS 1.2 or higher.",
      pluginId: "56203",
    },
    {
      id: uid(),
      scanId: batch3Id,
      scanLabel: batch3.label,
      scanDate: "2026-07-01T10:00:00Z",
      tool: "Nessus",
      host: "10.100.1.25",
      port: "445",
      protocol: "tcp",
      name: "SMB Signing Not Required",
      severity: "Medium",
      cvss: 5.0,
      cve: [],
      description: "SMB signing is not required on the remote server, allowing man-in-the-middle attacks.",
      solution: "Enforce SMB signing in host configuration.",
      pluginId: "57608",
    },
    {
      id: uid(),
      scanId: batch3Id,
      scanLabel: batch3.label,
      scanDate: "2026-07-01T10:00:00Z",
      tool: "Nessus",
      host: "10.100.2.12",
      port: "3306",
      protocol: "tcp",
      name: "MySQL Encryption in Transit Disabled",
      severity: "Medium",
      cvss: 5.9,
      cve: [],
      description: "The database connection is not encrypted in transit.",
      solution: "Enable SSL/TLS requirement for database users.",
      pluginId: "11993",
    },
    {
      id: uid(),
      scanId: batch3Id,
      scanLabel: batch3.label,
      scanDate: "2026-07-01T12:00:00Z",
      tool: "Burp Suite",
      host: "api.vaptlens.com",
      port: "443",
      protocol: "https",
      name: "CORS Misconfiguration Allows Arbitrary Origin Access",
      severity: "Medium",
      cvss: 6.5,
      cve: [],
      description: "Access-Control-Allow-Origin header mirrors incoming Origin dynamically with credentials allowed.",
      solution: "Do not dynamically mirror origins with credentials enabled.",
      pluginId: "issue-cors",
    },
    {
      id: uid(),
      scanId: batch3Id,
      scanLabel: batch3.label,
      scanDate: "2026-07-01T12:00:00Z",
      tool: "Burp Suite",
      host: "vaptlens.com",
      port: "443",
      protocol: "https",
      name: "Cookie Missing Secure Attribute",
      severity: "Medium",
      cvss: 4.8,
      cve: [],
      description: "Session identifiers and security cookies are set without the Secure attribute.",
      solution: "Set the Secure flag on all session cookies.",
      pluginId: "issue-cookie-sec",
    },
    {
      id: uid(),
      scanId: batch3Id,
      scanLabel: batch3.label,
      scanDate: "2026-07-01T10:00:00Z",
      tool: "Nessus",
      host: "10.100.2.5",
      port: "80",
      protocol: "tcp",
      name: "HTTP Server Wildcard SSL Certificate Expiration",
      severity: "Low",
      cvss: 3.2,
      cve: [],
      description: "The SSL certificate for the remote HTTP service will expire soon.",
      solution: "Renew the SSL certificate.",
      pluginId: "12345",
    },
    {
      id: uid(),
      scanId: batch3Id,
      scanLabel: batch3.label,
      scanDate: "2026-07-01T10:00:00Z",
      tool: "Nessus",
      host: "10.100.1.25",
      port: "445",
      protocol: "tcp",
      name: "SMB Registry Access Allowed",
      severity: "Low",
      cvss: 3.1,
      cve: [],
      description: "Remote access to the Windows registry is allowed, enabling reconnaissance.",
      solution: "Disable the Remote Registry service.",
      pluginId: "26922",
    },
    {
      id: uid(),
      scanId: batch3Id,
      scanLabel: batch3.label,
      scanDate: "2026-07-01T12:00:00Z",
      tool: "Burp Suite",
      host: "vaptlens.com",
      port: "443",
      protocol: "https",
      name: "Web Server Directory Indexing Enabled",
      severity: "Low",
      cvss: 3.1,
      cve: [],
      description: "Web server displays file lists for directories lacking index.html.",
      solution: "Disable directory listings (Options -Indexes).",
      pluginId: "issue-dir-index",
    },
    {
      id: uid(),
      scanId: batch3Id,
      scanLabel: batch3.label,
      scanDate: "2026-07-01T12:00:00Z",
      tool: "Burp Suite",
      host: "vaptlens.com",
      port: "443",
      protocol: "https",
      name: "X-Content-Type-Options Header Missing",
      severity: "Info",
      cvss: 0.0,
      cve: [],
      description: "The X-Content-Type-Options response header is not set to nosniff.",
      solution: "Send 'X-Content-Type-Options: nosniff' header.",
      pluginId: "issue-xcontent",
    },
    {
      id: uid(),
      scanId: batch3Id,
      scanLabel: batch3.label,
      scanDate: "2026-07-01T10:00:00Z",
      tool: "Nessus",
      host: "10.100.2.12",
      port: "22",
      protocol: "tcp",
      name: "SSH Server Banner Disclosure",
      severity: "Info",
      cvss: 0.0,
      cve: [],
      description: "The remote SSH server discloses its version banner.",
      solution: "Configure SSH to hide version details.",
      pluginId: "10092",
    },
    {
      id: uid(),
      scanId: batch3Id,
      scanLabel: batch3.label,
      scanDate: "2026-07-01T12:00:00Z",
      tool: "Burp Suite",
      host: "vaptlens.com",
      port: "443",
      protocol: "https",
      name: "HTTP Trace Method Enabled",
      severity: "Low",
      cvss: 3.5,
      cve: ["CVE-2004-2320"],
      description: "HTTP TRACE method is enabled, allowing Cross-Site Tracing.",
      solution: "Disable TRACE method in web server config.",
      pluginId: "issue-trace",
    },
  ];

  return {
    findings: [...q4Findings, ...q1Findings, ...q2Findings],
    batches: [batch1, batch2, batch3],
  };
}
