export var THEME_LIST = [
  {
    id: "dark",
    label: "Dark",
    base: "dark",
    group: "Dark",
    note: "",
    sw: ["#0a0b0d", "#171a1f", "#ffb020", "#ff4d6a", "#6ea2ff"],
  },
  {
    id: "light",
    label: "Light",
    base: "light",
    group: "Light",
    note: "",
    sw: ["#f3f4f6", "#f0f1f3", "#a15f00", "#c8173a", "#1d5fcf"],
  },
  {
    id: "cvd",
    label: "Colour-blind safe",
    base: "dark",
    group: "Accessible",
    note: "",
    sw: ["#0a0b0d", "#171a1f", "#ffb020", "#f5418e", "#6ea2ff"],
  },
  {
    id: "hc",
    label: "High contrast",
    base: "dark",
    group: "Accessible",
    note: "",
    sw: ["#000000", "#161616", "#ffc24d", "#ff8aa0", "#8ab4ff"],
  },
  {
    id: "midnight",
    label: "Midnight",
    base: "dark",
    group: "Dark",
    note: "codex / cosmic \u00b7 deep navy, periwinkle chrome",
    sw: ["#0a0f1e", "#141d35", "#8fb0ff", "#ff4d6a", "#6ea2ff"],
  },
  {
    id: "matrix",
    label: "Matrix",
    base: "dark",
    group: "Dark",
    note: "matrix / mono \u00b7 phosphor green on black",
    sw: ["#050907", "#0e1812", "#39e08f", "#ff4d6a", "#39e08f"],
  },
  {
    id: "neon",
    label: "Neon",
    base: "dark",
    group: "Dark",
    note: "neon / futuristic \u00b7 lime chrome, cyan data",
    sw: ["#0a0a10", "#171721", "#bbf351", "#ff4d6a", "#00bcff"],
  },
  {
    id: "teal",
    label: "Teal",
    base: "dark",
    group: "Dark",
    note: "sleek / bento fintech \u00b7 slate with deep-teal chrome",
    sw: ["#0f171e", "#1a2632", "#2ec4b6", "#ff4d6a", "#2ec4b6"],
  },
  {
    id: "paper",
    label: "Paper",
    base: "light",
    group: "Light",
    note: "paper / editorial \u00b7 warm ivory, ink-red chrome",
    sw: ["#f4efe4", "#f3ede1", "#a3321c", "#c8173a", "#1d5fcf"],
  },
  {
    id: "enterprise",
    label: "Enterprise",
    base: "light",
    group: "Light",
    note: "enterprise / ant \u00b7 cool blue-grey, royal-blue chrome",
    sw: ["#eef2f7", "#f3f6fa", "#1d4ed8", "#c8173a", "#1d4ed8"],
  },
  {
    id: "dramatic",
    label: "Dramatic",
    base: "dark",
    group: "Dark",
    note: "dramatic / roku \u00b7 zinc black, violet chrome",
    sw: ["#09090b", "#18181b", "#a78bfa", "#ff4d6a", "#a78bfa"],
  },
  {
    id: "graphite",
    label: "Graphite",
    base: "dark",
    group: "Dark",
    note: "bold / pacman \u00b7 neutral graphite, ocean-blue chrome",
    sw: ["#111111", "#1f1f1f", "#3fa7e8", "#ff4d6a", "#3fa7e8"],
  },
  {
    id: "arcade",
    label: "Arcade",
    base: "dark",
    group: "Dark",
    note: "sega / tetris \u00b7 indigo night, arcade-yellow chrome",
    sw: ["#0c0a24", "#1a1640", "#ffda14", "#ff4d6a", "#8f7bff"],
  },
  {
    id: "terracotta",
    label: "Terracotta",
    base: "light",
    group: "Light",
    note: "terracotta / cafe \u00b7 warm sand, fired-clay chrome",
    sw: ["#f6efe6", "#f3e9d8", "#a9532b", "#c8173a", "#1d5fcf"],
  },
  {
    id: "stitch",
    label: "Stitch",
    base: "light",
    group: "Light",
    note: "stitch / sketch \u00b7 bone canvas, pine chrome",
    sw: ["#edeade", "#f2f0e6", "#0b5c55", "#c8173a", "#0b5c55"],
  },
  {
    id: "material",
    label: "Material",
    base: "light",
    group: "Light",
    note: "material / shadcn \u00b7 lavender tonal surfaces, violet chrome",
    sw: ["#f7f2fa", "#f3edf7", "#6442d6", "#c8173a", "#6442d6"],
  },
  {
    id: "vintage",
    label: "Vintage",
    base: "light",
    group: "Light",
    note: "vintage / retro \u00b7 desktop-era silver, navy and teal chrome",
    sw: ["#c3c3c3", "#d6d6d6", "#006666", "#c8173a", "#1d3fae"],
  },
];
